apiVersion: apps/v1 # key value pairs
kind: Deployment # key value pairs

metadata: # Dictionary
  name: nginx-deployment
  labels:  # Dictionary
    app: nginx

spec: # Dictionary
  replicas: 3

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
        
    spec: 
      containers: # Multiple list 
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80