apiVersion: v1
kind: Service
metadata:
  name: my-alb-service
  
spec:
  type: LoadBalancer # Clasic (application alb)
  selector:
    app: myapp 
  ports:
    - name: http 
      port: 80 
      targetPort: 80
