apiVersion: v1
kind: Service
metadata:
  name: my-alb-service
  
spec:
  type: LoadBalancer # Clasic (application alb)
  selector:
    app: registration-app
  ports:
    - name: http 
      port: 80 
      targetPort: 8080
