apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: #dictionary
    app: myapp

spec:
    containers:
      - name: myapp
        image: rsakyi27/rennietechs-app:v1.0.0
        ports:
      - containerPort: 80